services:
  - type: web
    name: obesity-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    envVars:
      - key: DATABASE_URL
        fromDatabase: your-database
    plan: free
